// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"test-bot/app"
	"test-bot/config"
	"test-bot/feed"
	"test-bot/logger"
	"test-bot/login"
)

// Injectors from wire.go:

func InitializeApp() (app.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	loginRepository, err := login.NewLoginRepository(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	feedRepository := feed.NewFeedRepository(configConfig, loggerLogger)
	appApp := app.NewTestBotApp(loginRepository, feedRepository)
	return appApp, nil
}
